"""empty message

Revision ID: d53f1afc01fe
Revises: f53bc39db3cb
Create Date: 2023-06-20 14:38:34.324254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53f1afc01fe'
down_revision = 'f53bc39db3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('don_refno', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('don_paygate_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('don_paygate_response')
        batch_op.drop_column('don_refno')

    # ### end Alembic commands ###
