"""empty message

Revision ID: f53bc39db3cb
Revises: dd07e411fcf5
Create Date: 2023-06-20 14:29:47.617569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53bc39db3cb'
down_revision = 'dd07e411fcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('don_fullname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('don_emailL', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('don_emailL')
        batch_op.drop_column('don_fullname')

    # ### end Alembic commands ###
